version: '3'
services:
  redis:
    image: redis:latest
    container_name: ruins-redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_NAME=${REDIS_NAME}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
